### ISSUE TITLE
Export-CrmSolution : A positional parameter cannot be found that accepts argument 'True'.

### ISSUE THREAD

**Issue by DingBong** [seanmcne/Microsoft.Xrm.Data.PowerShell#277]
Hi,

I'm trying to export an unmanaged solution using the `Export-CrmSolution` cmdlet. When I run the command, I receive the error `Export-CrmSolution : A positional parameter cannot be found that accepts argument 'True'`. 

Here is the cmdlet that's failing:
`Export-CrmSolution -conn  $crmConnection -SolutionName $crmSolution -SolutionFilePath $outputDir -SolutionZipFileName "$($crmSolution)_managed.zip" -Managed -ExportAutoNumberingSettings $true -ExportCalendarSettings $true -ExportCustomizationSettings $true -ExportEmailTrackingSettings $true -ExportGeneralSettings $true -ExportMarketingSettings $true -ExportOutlookSynchronizationSettings $true -ExportRelationshipRoles $true -ExportIsvConfig $true -ExportSales $true -Verbose`

The trace provides the following information:
```
Source	: Microsoft.Xrm.Tooling.CrmConnectControl
Method	: ReadCredentials
Date	: 1/17/2018
Time	: 9:41:57 AM
Error	: Failed to read the saved credentials.
Stack Trace	: at Microsoft.Xrm.Tooling.CrmConnectControl.Utility.CredentialManager.ReadCredentials(String target)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.LoadConfigFromFile(Boolean readLocalFirst)
======================================================================================================================

Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	1/17/2018 9:41:57 AM  SetConfigKeyInfo, Key Count = 9
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	1/17/2018 9:41:57 AM  Using CRM deployment type Prem
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	1/17/2018 9:41:57 AM  SSL Connection = False
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	1/17/2018 9:41:57 AM  Discovery URI is = http://*****/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:57 AM  DiscoverOrganizations - Initializing Discovery Server Object with http://*****/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:57 AM  DiscoverOrganizations - attempting to connect to CRM server @ http://*****/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:57 AM  DiscoverOrganizations - created CRM server proxy configuration for http://*****/XRMServices/2011/Discovery.svc - duration: 00:00:00.1250144
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:57 AM  DiscoverOrganizations - proxy requiring authentication type : ActiveDirectory 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:57 AM  DiscoverOrganizations - service proxy created - total create duration: 00:00:00.1250144
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  DiscoverOrganizations - Discovery Server Get Orgs Call Complete - Elapsed:00:00:02.3906854
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	1/17/2018 9:41:59 AM  Found 1 Org(s)
Microsoft.Xrm.Tooling.CrmConnectControl	Verbose	16	1/17/2018 9:41:59 AM  DiscoveryServer indicated organization service location = http://****/org/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	1/17/2018 9:41:59 AM  Organization Service URI is = http://*****/org/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	1/17/2018 9:41:59 AM  Validating connection to Microsoft Dynamics CRM...
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  Process is bypassed.. OrgDetail object was provided
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:59 AM  DiscoveryServer indicated organization service location = http://*****/org/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  Organization Service URI is = http://*****/org/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - Initializing Organization Service Object
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - Requesting connection to Org with CRM Version: 8.2.2.112
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - Using ISerivceManagement
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - attempting to connect to CRM server @ http://*****/org/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - created CRM server proxy configuration for http://*****/org/XRMServices/2011/Organization.svc - duration: 00:00:00.0781872
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - proxy requiring authentication type : ActiveDirectory 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - service proxy created - total create duration: 00:00:00.0781872
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  ConnectAndInitCrmOrgService - Proxy created, total elapsed time: 00:00:00.0781872
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  Beginning Validation of CRM Connection
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	1/17/2018 9:41:59 AM  Validation of CRM Connection Complete, total duration: 00:00:00.1249558
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	1/17/2018 9:41:59 AM  New Batch Manager Created, Max #of Batches:50000, Max #of RequestsPerBatch:5000
```
The Server is On-Premise; it's a development server running on HTTP:80.

When I remove the `-Export****` switches from the parameters, it works properly (with the same credentials). Check the following script:
`Export-CrmSolution -conn  $crmConnection -SolutionName $crmSolution -SolutionFilePath $outputDir -SolutionZipFileName "$($crmSolution)_managed.zip" -Managed -Verbose`

I can't seem to find any documentation on this cmdlet, and the `Get-Help Export-CrmSolution -Detailed` doesn't give me tips to fix a possible syntax error. Can someone shed some light on this?

Thanks,

Wouter.

PS. The failing PS-Script below (I'm importing the `Microsoft.Xrm.Data.PowerShell `module in a previous script:
```
Param(
    [string] $crmUser,
    [string] $crmPassword,
    [string] $crmUrl,
    [int] $timeOut,
    [string] $outputDir,
    [string] $crmSolution,
	[string] $crmOrganizationName,
	[bool] $managed,
	[bool] $unmanaged
)

Write-Output "Logging in as  $crmUser with password  $crmPassword"
 $securePwd = ConvertTo-SecureString  $crmPassword -AsPlainText -Force
 $crmCredential = New-Object System.Management.Automation.PSCredential( $crmUser,  $securePwd)

Write-Output "Connecting to CRM"
 $crmConnection = Get-CrmConnection -ServerUrl  $crmUrl -OrganizationName  $crmOrganizationName -Verbose -Credential  $crmCredential -MaxCrmConnectionTimeOutMinutes  $timeOut

Write-Output "Export CRM Solution  $crmSolution to directory  $outputDir"

if( $managed) {
	Export-CrmSolution -conn  $crmConnection -SolutionName $crmSolution -SolutionFilePath $outputDir -SolutionZipFileName "$($crmSolution)_managed.zip" -Managed -ExportAutoNumberingSettings $true -ExportCalendarSettings $true -ExportCustomizationSettings $true -ExportEmailTrackingSettings $true -ExportGeneralSettings $true -ExportMarketingSettings $true -ExportOutlookSynchronizationSettings $true -ExportRelationshipRoles $true -ExportIsvConfig $true -ExportSales $true -Verbose
}

if( $unmanaged) {
	Export-CrmSolution -conn  $crmConnection -SolutionName $crmSolution -SolutionFilePath $outputDir -SolutionZipFileName "$($crmSolution)_unmanaged.zip" -ExportAutoNumberingSettings $true -ExportCalendarSettings $true -ExportCustomizationSettings $true -ExportEmailTrackingSettings $true -ExportGeneralSettings $true -ExportMarketingSettings $true -ExportOutlookSynchronizationSettings $true -ExportRelationshipRoles $true -ExportIsvConfig $true -ExportSales $true -Verbose
}
```

**Comment by seanmcne** [comment]
those are all switch parameters - you don't need to supply a "True" value, the presence of the switch sets it to true and lack of the switch parameter means false.  For instance: 

Export-CrmSolution -conn $crmConnection -SolutionName $crmSolution -SolutionFilePath $outputDir -SolutionZipFileName "$($crmSolution)_managed.zip" -Managed -ExportAutoNumberingSettings -ExportCalendarSettings -ExportCustomizationSettings -ExportOutlookSynchronizationSettings -ExportIsvConfig -Verbose

You can get syntax examples by running: 
get-help Export-CrmSolution -Examples

SYNTAX
    Export-CrmSolution [-conn <CrmServiceClient>] [-SolutionName] <String> [[-SolutionFilePath] <String>] [-SolutionZipFileName 
    <String>] [-Managed <SwitchParameter>] [-TargetVersion <String>] [-ExportAutoNumberingSettings <SwitchParameter>] 
    [-ExportCalendarSettings <SwitchParameter>] [-ExportCustomizationSettings <SwitchParameter>] [-ExportEmailTrackingSettings 
    <SwitchParameter>] [-ExportGeneralSettings <SwitchParameter>] [-ExportMarketingSettings <SwitchParameter>] 
    [-ExportOutlookSynchronizationSettings <SwitchParameter>] [-ExportRelationshipRoles <SwitchParameter>] [-ExportIsvConfig 
    <SwitchParameter>] [-ExportSales <SwitchParameter>] [<CommonParameters>]

Hope that helps - thanks!

**Comment by DingBong** [comment]
Hi Sean,

Thanks for the reply. I changed the cmdLet and it worked right away. I wasn't aware you didn't have to set a `$true` switch, if the parameter is a SwitchParameter. I've corrected my script.

Thanks!

**Comment by seanmcne** [comment]
Excellent- glad to hear it’s working!
